// ==================================================================
// PRINT RASTER RENDERER
// ------------------------------------------------------------------
//
// Produces a PNG suitable for high-quality print at DIN A0 landscape
// (1189 × 841 mm) using the Cahill-Concialdi bat projection.
//
// Usage:  node render.mjs
// Output: cahill-concialdi-a0.png  (14043 × 9933 px, 300 DPI)
//
// Requires: canvas, sharp, complex.js  (npm install)
// ------------------------------------------------------------------

import { readFileSync }    from 'fs';
import { Complex }        from 'complex.js';
import { createCanvas, registerFont } from 'canvas';
import sharp              from 'sharp';
import { open as openShp } from 'shapefile';
import { COUNTRY_LANG, LANG_NE_FIELD, LANG_FONT, RTL_LANGS } from './localnames.mjs';

// node-canvas cannot use CJK glyphs via fontconfig from TTC variable fonts.
// Register the CJK collection once under a single family name.
registerFont(
  '/usr/share/fonts/google-noto-sans-cjk-vf-fonts/NotoSansCJK-VF.ttc',
  { family: 'Noto Sans CJK' },
);

// cahill-conformal.mjs uses Complex as a browser global; provide it here
globalThis.Complex = Complex;

import { Point, LatLon }                           from './data-types.mjs';
import { MAX_COLOR_VALUE, DEGS_IN_CIRCLE, TWO_PI } from './globals.mjs';
import { MAP_AREAS, project,
         MAP_VIEW_ORIGIN, MAP_WIDTH,
         MAP_HEIGHT, MAP_TILT }                    from './concialdi.mjs';

// ------------------------------------------------------------------
// Output dimensions

const DPI          = 300;
const MM_PER_INCH  = 25.4;

// Convert millimetres → canvas pixels at the current DPI.
// All size constants below are expressed in mm so they stay correct if DPI changes.
const mm = v => v * DPI / MM_PER_INCH;
//const WIDTH_MM     = 1682;   // DIN 2A0 landscape
//const HEIGHT_MM    = 1189;
const WIDTH_MM     = 1189;   // DIN A0 landscape
const HEIGHT_MM    = 841;

const CANVAS_WIDTH  = Math.round(WIDTH_MM  / MM_PER_INCH * DPI);
const CANVAS_HEIGHT = Math.round(HEIGHT_MM / MM_PER_INCH * DPI);

const SOURCE_FILE = '../HYP_HR_SR_W_DR.tif';
const OUTPUT_FILE = 'cahill-concialdi-a0.png';

const NUM_DEST_CHANNELS = 4; // RGBA in canvas ImageData

// Pre-built localised-name lookup: geonamesId (string) → local name.
// Generated by:  node build-localnames.mjs
const altNames = JSON.parse(readFileSync(new URL('./ne-localnames.json', import.meta.url)));

// ================================================================
// CITY RENDERING CONSTANTS — edit these freely
// ================================================================

// Path to the Natural Earth populated places shapefile
const CITY_SHP = '../ne_10m_populated_places.shp';

// --- Dots ---
// Dots are drawn for ALL cities in the shapefile regardless of population.
// Their radius is log-scaled over the full population range of the dataset.
const CITY_DOT_RADIUS_MIN = mm(0.085);  // mm — for the smallest cities
const CITY_DOT_RADIUS_MAX = mm(1.0);    // mm — for the largest cities (~35 M)
const CITY_DOT_COLOR      = 'rgba(0, 0, 0, 0.50)';

// --- Label placement ---
// Only cities at or above this population are label candidates.
// The greedy algorithm may further cull labels that can't be placed cleanly.
const CITY_MIN_POPULATION = 10_000;

// Maximum displacement of a label's anchor from its dot edge.
// Labels with no clean candidate position within this radius are culled.
const CITY_LABEL_MAX_DISP = mm(3.4);

// Minimum gap between the dot edge and the nearest edge of its label.
const CITY_LABEL_GAP = mm(0.85);

// Padding added to every side of a label's bounding box before overlap testing.
// Scales INVERSELY with log-population: small cities need more breathing room
// to justify their presence; large cities can be packed tightly.
const CITY_LABEL_PADDING_MAX = mm(1.35);  // at CITY_MIN_POPULATION
const CITY_LABEL_PADDING_MIN = mm(0.085); // at max population (~35 M)

// Candidate anchor angles tried for each label, at 15° increments.
// 0° = east (right of dot); alternates ±offset so nearby angles are tried
// before far ones: 0, -15, 15, -30, 30, …, -165, 165, 180.
const CITY_LABEL_ANGLES = [0,
  ...[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165].flatMap(d => [-d, d]),
  180].map(d => d * Math.PI / 180);

// Number of distance steps tried at each angle, spaced evenly from
// (dotRadius + CITY_LABEL_GAP) up to (dotRadius + CITY_LABEL_MAX_DISP).
const CITY_LABEL_DIST_STEPS = 3;

// When scoring candidate positions, only consider already-placed labels
// whose bbox centre falls within this radius. Labels farther away
// are irrelevant to local crowding and excluding them keeps scoring fast.
const CITY_LABEL_SCORE_RADIUS = mm(3.4);

// Dot-radius threshold above which dots use a radial gradient + outline
// instead of a plain filled circle. Below this the dot is too small to matter.
const CITY_DOT_GRADIENT_THRESHOLD = mm(0.5);

// --- Font ---
// 0.75 mm ≈ 9 pt at 300 DPI — legible on photo paper for isolated labels.
const CITY_FONT_FAMILY   = 'DejaVu Sans';
const CITY_FONT_SIZE_MIN = mm(0.75);  // at CITY_MIN_POPULATION
const CITY_FONT_SIZE_MAX = mm(2.7);   // at ~35 M population

// Complex labels (dots at or above CITY_DOT_GRADIENT_THRESHOLD): white fill + dark halo
const CITY_LABEL_COLOR  = 'rgba(255, 255, 255, 0.92)';
const CITY_HALO_WIDTH   = mm(0.17);  // half-width of dark outline; set to 0 to disable
const CITY_HALO_COLOR   = 'rgba(0, 0, 0, 0.65)';
// Simple labels (dots below CITY_DOT_GRADIENT_THRESHOLD): plain fill, no halo
const CITY_LABEL_COLOR_SIMPLE = 'rgba(0, 0, 0, 0.92)';

// Leader line connecting each label to its dot
const CITY_LEADER_WIDTH = mm(0.085);
const CITY_LEADER_COLOR = 'rgba(0, 0, 0, 1.0)';

// ================================================================
// SCALE BAR CONSTANTS — edit these freely
// ================================================================

// GPS coordinate of the LEFT anchor of the scale bar.
// North Atlantic void, west of UK and south of Iceland.
const SCALE_BAR_ANCHOR_LAT =  30.2;   // °N
const SCALE_BAR_ANCHOR_LON = -50;   // °W

// Physical length of the bar on the printed page.
const SCALE_BAR_LENGTH_MM  = 100;   // mm

const SCALE_BAR_FONT_SIZE  = mm(3.2);   // label text height
const SCALE_BAR_TICK_H     = mm(1.0);   // height of end tick marks
const SCALE_BAR_COLOR      = 'rgba(255, 255, 255, 0.75)';
const SCALE_BAR_SHADOW     = 'rgba(0,   0,   0,   0.50)';

// ------------------------------------------------------------------
// Load source TIFF as raw RGB

process.stdout.write('Loading source image … ');
const { data: srcData, info: srcInfo } =
  await sharp(SOURCE_FILE).raw().toBuffer({ resolveWithObject: true });

const SOURCE_PPD = srcInfo.width / DEGS_IN_CIRCLE; // 60 for 21600 px wide
console.log(`${srcInfo.width}×${srcInfo.height} px, ${SOURCE_PPD} PPD`);

// ------------------------------------------------------------------
// Canvas + ImageData setup

const canvasPerSvg  = CANVAS_WIDTH / MAP_WIDTH;
const mapHeightPx   = MAP_HEIGHT * canvasPerSvg;
const yOffsetSvg    = (CANVAS_HEIGHT - mapHeightPx) / 2 / canvasPerSvg;

// Adjusted view origin centres the map vertically within the A0 canvas
const viewOrigin = new Point(MAP_VIEW_ORIGIN.x, MAP_VIEW_ORIGIN.y + yOffsetSvg);

const canvas    = createCanvas(CANVAS_WIDTH, CANVAS_HEIGHT);
const ctx       = canvas.getContext('2d');
const imageData = ctx.createImageData(CANVAS_WIDTH, CANVAS_HEIGHT);

// White background; alpha=0 marks "unwritten" for seam gap detection later.
for (let i = 0; i < imageData.data.length; i += 4) {
  imageData.data[i] = imageData.data[i + 1] = imageData.data[i + 2] = 255;
  imageData.data[i + 3] = 0;
}

// ------------------------------------------------------------------
// MapCell — adapted from map-raster.mjs, closes over canvas/source globals

class MapCell {

  constructor(swLatLon, cellCorners, maskCorners) {
    this.swLatLon    = swLatLon;
    this.cellCorners = cellCorners;
    this.maskCorners = maskCorners;

    const isNorthPolar = cellCorners[2].isEqualTo(cellCorners[3]);
    const isSouthPolar = cellCorners[0].isEqualTo(cellCorners[1]);
    this.isPolar      = isNorthPolar || isSouthPolar;
    this.isNorthPolar = isNorthPolar;
  }

  drawCell() {
    const xs   = this.maskCorners.map(p => p.x);
    const ys   = this.maskCorners.map(p => p.y);
    const minX = Math.floor(Math.min(...xs));
    const maxX = Math.ceil (Math.max(...xs));
    const minY = Math.floor(Math.min(...ys));
    const maxY = Math.ceil (Math.max(...ys));

    for   (let x = minX; x <= maxX; x++) {
      for (let y = minY; y <= maxY; y++) {

        if (x < 0 || x >= CANVAS_WIDTH || y < 0 || y >= CANVAS_HEIGHT) continue;

        const pixelPos = new Point(x, y);
        if (!this.isInMask(pixelPos)) continue;

        const latLon = this.isPolar
          ? this.getPolarInverseLatLon(pixelPos)
          : this.getInverseLatLon     (pixelPos);

        // Positive modulo for longitude: JS % returns negative for negative inputs,
        // which causes out-of-bounds reads when floating-point drift pushes lon < -180.
        const lonNorm = ((latLon.lon + DEGS_IN_CIRCLE / 2) % DEGS_IN_CIRCLE + DEGS_IN_CIRCLE) % DEGS_IN_CIRCLE;
        const srcX = Math.min(Math.floor(SOURCE_PPD * lonNorm), srcInfo.width  - 1);
        // Clamp latitude so polar drift never produces a negative or overflow row index.
        const srcY = Math.max(0, Math.min(Math.floor(SOURCE_PPD * (DEGS_IN_CIRCLE / 4 - latLon.lat)), srcInfo.height - 1));

        const srcIdx = srcInfo.channels * (srcY * srcInfo.width + srcX);
        const dstIdx = NUM_DEST_CHANNELS * (y   * CANVAS_WIDTH  + x  );

        imageData.data[dstIdx    ] = srcData[srcIdx    ];
        imageData.data[dstIdx + 1] = srcData[srcIdx + 1];
        imageData.data[dstIdx + 2] = srcData[srcIdx + 2];
        imageData.data[dstIdx + 3] = MAX_COLOR_VALUE;
      }
    }
  }

  isInMask(point) {
    let numIntersections = 0;
    for (let i = 0; i < this.maskCorners.length; i++) {
      const a = this.maskCorners[i];
      const b = this.maskCorners[(i + 1) % this.maskCorners.length];
      if (
        point.x >= Math.min(a.x, b.x) &&
        point.x <  Math.max(a.x, b.x)
      ) {
        if (
          point.y >= Math.max(a.y, b.y) ||
          point.y >= Math.min(a.y, b.y) &&
          point.y >= a.y + (point.x - a.x) / (b.x - a.x) * (b.y - a.y)
        ) numIntersections++;
      }
    }
    return numIntersections % 2 === 1;
  }

  getInverseLatLon(point) {
    const c = this.cellCorners;
    const J = point.x - c[0].x,  K = point.y - c[0].y;
    const L = c[1].x  - c[0].x,  M = c[1].y  - c[0].y;
    const N = c[3].x  - c[0].x,  P = c[3].y  - c[0].y;
    const Q = c[0].x  + c[2].x - c[1].x - c[3].x;
    const R = c[0].y  + c[2].y - c[1].y - c[3].y;

    const a =           - L*R + Q*M;
    const b = J*R + N*M - L*P - Q*K;
    const cc = J*P - N*K;

    const disc = Math.sqrt(b*b - 4*a*cc);
    const x1 = (-b + disc) / (2*a),  y1 = (J - L*x1) / (N + Q*x1);
    const x2 = (-b - disc) / (2*a),  y2 = (J - L*x2) / (N + Q*x2);

    const latLon = (0 <= x1 && x1 <= 1 && 0 <= y1 && y1 <= 1)
      ? new LatLon(y1, x1)
      : new LatLon(y2, x2);
    latLon.lat += this.swLatLon.lat;
    latLon.lon += this.swLatLon.lon;
    return latLon;
  }

  getPolarInverseLatLon(point) {
    const c = this.cellCorners;
    const cellHeight = c[2].getDistanceTo(c[1]);
    const relLat = this.isNorthPolar
      ? 1 - c[2].getDistanceTo(point) / cellHeight
      :     c[1].getDistanceTo(point) / cellHeight;

    let cellWidth = this.isNorthPolar
      ? c[2].getAngleTo(c[0]) - c[2].getAngleTo(c[1])
      : c[1].getAngleTo(c[2]) - c[1].getAngleTo(c[3]);
    if (cellWidth < 0) cellWidth += TWO_PI;

    let relLon = this.isNorthPolar
      ? +(c[2].getAngleTo(c[0]) - c[2].getAngleTo(point))
      : -(c[1].getAngleTo(c[3]) - c[1].getAngleTo(point));
    if (relLon < 0) relLon += TWO_PI;
    relLon /= cellWidth;

    return new LatLon(this.swLatLon.lat + relLat, this.swLatLon.lon + relLon);
  }
}

// ------------------------------------------------------------------
// Render

function drawMapArea(area, idx) {
  const antiMeridianAdjust = area.hasAntimeridian ? DEGS_IN_CIRCLE : 0;
  const startLon = Math.floor(area.swCorner.lon);
  const endLon   = Math.ceil (area.neCorner.lon) + antiMeridianAdjust;

  for (let lat = area.swCorner.lat; lat < area.neCorner.lat; lat++) {
    for (let lon = startLon; lon < endLon; lon++) {

      const maskedLonW = Math.max(lon,     area.swCorner.lon);
      const maskedLonE = Math.min(lon + 1, area.neCorner.lon + antiMeridianAdjust);

      const corners = [
        [lat,     lon    ], [lat,     lon + 1],
        [lat + 1, lon + 1], [lat + 1, lon    ],
        [lat,     maskedLonW], [lat,     maskedLonE],
        [lat + 1, maskedLonE], [lat + 1, maskedLonW],
      ]
      .map(([la, lo]) => new LatLon(la, lo))
      .map(latLon =>
        project(latLon, idx)
          .rotate(MAP_TILT)
          .translate(viewOrigin)
          .scale(canvasPerSvg)
      );

      new MapCell(
        new LatLon(lat, lon),
        corners.slice(0, 4),
        corners.slice(4, 8),
      ).drawCell();
    }
  }
}

// ================================================================
// CITY LABEL HOOKS — replace these when adding localised name data
// ================================================================

// Returns the display name for a city in its local language.
// Priority: GeoNames short name → GeoNames preferred name → NE field → NAME (English).
function getCityLabel(props) {
  const lang = COUNTRY_LANG[props.ADM0_A3];
  if (!lang) return props.NAME;

  const gnId = String(props.GEONAMESID || '');
  if (gnId && gnId !== '0') {
    const gn = altNames[gnId];
    if (gn) return gn;
  }

  const neField = LANG_NE_FIELD[lang];
  if (neField && props[neField]) return props[neField];

  return props.NAME;
}

// Returns the CSS font-family for the script used by the given city's language.
function getCityFont(props) {
  const lang = COUNTRY_LANG[props.ADM0_A3];
  return (lang && LANG_FONT[lang]) || CITY_FONT_FAMILY;
}

// ================================================================
// MAP BOUNDARY
// ================================================================

// Builds the outer boundary of the projection as an array of canvas-coordinate
// Points. Mirrors drawBackground() in map-vector.mjs exactly.
function buildMapBoundaryPts() {
  const c = pt => pt.rotate(MAP_TILT).translate(viewOrigin).scale(canvasPerSvg);
  const pts = [];

  pts.push(c(project(new LatLon(MAP_AREAS[5].neCorner.lat, MAP_AREAS[5].swCorner.lon), 5)));
  for (let lat = 0; lat >= -DEGS_IN_CIRCLE / 4; lat--)
    pts.push(c(project(new LatLon(lat, MAP_AREAS[5].swCorner.lon), 5)));
  for (let lon = MAP_AREAS[7].neCorner.lon; lon >= MAP_AREAS[7].swCorner.lon; lon--)
    pts.push(c(project(new LatLon(MAP_AREAS[7].neCorner.lat, lon))));
  pts.push(c(project(MAP_AREAS[6].neCorner, 6)));
  for (let lon = MAP_AREAS[8].swCorner.lon; lon <= MAP_AREAS[8].neCorner.lon; lon++)
    pts.push(c(project(new LatLon(MAP_AREAS[8].swCorner.lat, lon), 8)));
  pts.push(c(project(MAP_AREAS[8].neCorner)));
  for (let lon = MAP_AREAS[9].neCorner.lon; lon >= MAP_AREAS[9].swCorner.lon; lon--)
    pts.push(c(project(new LatLon(MAP_AREAS[9].neCorner.lat, lon), 9)));
  for (let lat = -DEGS_IN_CIRCLE / 4; lat <= 0; lat++)
    pts.push(c(project(new LatLon(lat, MAP_AREAS[11].neCorner.lon), 11)));
  pts.push(c(project(MAP_AREAS[10].neCorner)));
  for (let lat = 0; lat < DEGS_IN_CIRCLE / 4; lat++)
    pts.push(c(project(new LatLon(lat, MAP_AREAS[4].neCorner.lon), 4)));
  for (let lat = DEGS_IN_CIRCLE / 4; lat >= 0; lat--)
    pts.push(c(project(new LatLon(lat, MAP_AREAS[0].swCorner.lon))));
  pts.push(c(project(MAP_AREAS[5].neCorner)));

  return pts;
}

// Ray-casting point-in-polygon test against the map boundary polygon.
function isInsideMap(pts, x, y) {
  let inside = false;
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const { x: xi, y: yi } = pts[i];
    const { x: xj, y: yj } = pts[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi)
      inside = !inside;
  }
  return inside;
}

// ================================================================
// CITY LABEL RENDERING
// ================================================================

async function drawCityLabels() {

  // Log-scale helper: maps a population to [0, 1]
  const LOG_MAX       = Math.log(35_676_000);  // POP_MAX of Tokyo in this dataset
  const LOG_MIN_LABEL = Math.log(CITY_MIN_POPULATION);
  const logT = pop =>
    Math.min(1, Math.max(0, (Math.log(Math.max(pop, 1)) - LOG_MIN_LABEL) / (LOG_MAX - LOG_MIN_LABEL)));

  const mapBoundary = buildMapBoundaryPts();

  // --- Phase 1: load and project label candidates ---
  // Dots are only drawn for cities that receive a label (Phase 3),
  // so we only need to track label candidates here.

  const labelCandidates = [];

  const source = await openShp(CITY_SHP, CITY_SHP.replace(/\.shp$/i, '.dbf'), { encoding: 'utf-8' });
  for (;;) {
    const { done, value: feature } = await source.read();
    if (done) break;
    if (feature.geometry?.type !== 'Point') continue;

    const props = feature.properties;
    // POP_MIN is the city-proper figure; POP_MAX is inconsistently sourced
    // (sometimes metro, sometimes wider agglomeration) and can be misleading.
    // Fall back to POP_MAX only for the ~21 records where POP_MIN is missing.
    const pop = props.POP_MIN > 0 ? props.POP_MIN : Math.max(props.POP_MAX, 0);
    if (pop < CITY_MIN_POPULATION) continue;

    const [lon, lat] = feature.geometry.coordinates;

    let pt;
    try {
      pt = project(new LatLon(lat, lon))
        .rotate(MAP_TILT)
        .translate(viewOrigin)
        .scale(canvasPerSvg);
    } catch { continue; }

    if (pt.x < 0 || pt.x >= CANVAS_WIDTH || pt.y < 0 || pt.y >= CANVAS_HEIGHT) continue;

    const t      = logT(pop);
    const dotR   = CITY_DOT_RADIUS_MIN + t * (CITY_DOT_RADIUS_MAX - CITY_DOT_RADIUS_MIN);
    const label  = getCityLabel(props);
    const font   = getCityFont(props);
    const fontSize = Math.round(CITY_FONT_SIZE_MIN + t * (CITY_FONT_SIZE_MAX - CITY_FONT_SIZE_MIN));

    ctx.font = `${fontSize}px ${font}`;
    const labelW = ctx.measureText(label).width;

    // Per-city padding: inversely proportional to log-population so that
    // small cities need more surrounding space to survive placement.
    const padding = CITY_LABEL_PADDING_MAX - t * (CITY_LABEL_PADDING_MAX - CITY_LABEL_PADDING_MIN);

    const rtl = RTL_LANGS.has(COUNTRY_LANG[props.ADM0_A3]);
    labelCandidates.push({ pt, dotR, pop, t, fontSize, font, label, labelW, labelH: fontSize, padding, rtl });
  }

  // --- Phase 2: greedy label placement in descending population order ---
  //
  // High-population cities are placed first and claim the best nearby slots.
  // Small cities fill remaining gaps or are culled — implementing the
  // "dominant spring" behaviour. Candidates whose anchor falls outside the
  // map boundary are skipped, so labels never start outside the projection.

  labelCandidates.sort((a, b) => b.pop - a.pop);

  const placedBboxes = [];
  const placements   = [];

  for (const city of labelCandidates) {
    const { pt, dotR, labelW, labelH, padding } = city;

    const minDist = dotR + CITY_LABEL_GAP;
    const maxDist = dotR + CITY_LABEL_MAX_DISP;
    const step    = CITY_LABEL_DIST_STEPS < 2
      ? 0
      : (maxDist - minDist) / (CITY_LABEL_DIST_STEPS - 1);

    // Collect all non-overlapping candidates across every angle × distance combo,
    // then pick the one whose bbox center is furthest from the nearest placed bbox.
    // This naturally avoids label clusters rather than just taking the first match.
    let bestCandidate = null;
    let bestScore     = -Infinity;

    for (let di = 0; di < CITY_LABEL_DIST_STEPS; di++) {
      const dist = minDist + di * step;

      for (const angle of CITY_LABEL_ANGLES) {
        const ax = pt.x + Math.cos(angle) * dist;
        const ay = pt.y + Math.sin(angle) * dist;

        if (!isInsideMap(mapBoundary, ax, ay)) continue;

        const lx = Math.cos(angle) >= 0 ? ax : ax - labelW;
        const ly = ay;  // textBaseline = 'middle'

        const bbox = {
          x: lx          - padding,
          y: ly - labelH / 2 - padding,
          w: labelW      + padding * 2,
          h: labelH      + padding * 2,
        };

        const overlaps = placedBboxes.some(b =>
          bbox.x         < b.x + b.w &&
          bbox.x + bbox.w > b.x      &&
          bbox.y         < b.y + b.h &&
          bbox.y + bbox.h > b.y
        );
        if (overlaps) continue;

        // Score = distance to the nearest already-placed bbox center.
        // With no placed labels yet, use Infinity (any position is fine).
        const cx = bbox.x + bbox.w / 2;
        const cy = bbox.y + bbox.h / 2;
        const scoreR2 = CITY_LABEL_SCORE_RADIUS * CITY_LABEL_SCORE_RADIUS;
        const score = placedBboxes.reduce((minD, b) => {
          const dx = cx - (b.x + b.w / 2);
          const dy = cy - (b.y + b.h / 2);
          const d2 = dx * dx + dy * dy;
          return d2 <= scoreR2 ? Math.min(minD, d2) : minD;
        }, Infinity);
        // Infinity means no placed label is within the radius — treat as best possible

        if (score > bestScore) {
          bestScore     = score;
          bestCandidate = { bbox, lx, ly, ax, ay };
        }
      }
    }

    if (bestCandidate) {
      const { bbox, lx, ly, ax, ay } = bestCandidate;
      placedBboxes.push(bbox);
      placements.push({ city, lx, ly, ax, ay });
    }
  }

  // --- Phase 3: draw dots for placed cities only ---
  // Sort ascending by dotR so larger dots are painted last (on top).

  const placementsByDotSize = placements.slice().sort((a, b) => a.city.dotR - b.city.dotR);

  for (const { city: { pt, dotR } } of placementsByDotSize) {
    ctx.beginPath();
    ctx.arc(pt.x, pt.y, dotR, 0, TWO_PI);

    if (dotR >= CITY_DOT_GRADIENT_THRESHOLD) {
      const g = ctx.createRadialGradient(pt.x, pt.y, 0, pt.x, pt.y, dotR * 1.1);
      g.addColorStop(0,    'rgba(255, 255, 255, 0.20)'); // center
      g.addColorStop(0.75, 'rgba(255, 255, 255, 0.70');  // body colour
      ctx.fillStyle = g;
      ctx.fill();
      ctx.strokeStyle = CITY_DOT_COLOR;
      ctx.lineWidth   = Math.max(mm(0.17), dotR * 0.2);
      ctx.stroke();
    } else {
      ctx.fillStyle = CITY_DOT_COLOR;
      ctx.fill();
    }
  }

  // --- Phase 4: draw labels, clipped to the map boundary ---

  ctx.save();
  ctx.beginPath();
  ctx.moveTo(mapBoundary[0].x, mapBoundary[0].y);
  for (let i = 1; i < mapBoundary.length; i++)
    ctx.lineTo(mapBoundary[i].x, mapBoundary[i].y);
  ctx.closePath();
  ctx.clip();

  // Leader lines — draw first so labels render on top
  ctx.lineWidth   = CITY_LEADER_WIDTH;
  ctx.strokeStyle = CITY_LEADER_COLOR;
  for (const { city: { pt, dotR }, ax, ay } of placements) {
    const angle = Math.atan2(ay - pt.y, ax - pt.x);
    ctx.beginPath();
    ctx.moveTo(pt.x + Math.cos(angle) * dotR, pt.y + Math.sin(angle) * dotR);
    ctx.lineTo(ax, ay);
    ctx.stroke();
  }

  ctx.textBaseline = 'middle';

  for (const { city, lx, ly } of placements) {
    ctx.font = `${city.fontSize}px ${city.font}`;

    // RTL text (Arabic, Hebrew, Urdu, Persian): canvas textAlign='start' anchors
    // at the RIGHT edge when direction='rtl', so shift x to lx + labelW.
    if (city.rtl) ctx.direction = 'rtl';
    const tx = city.rtl ? lx + city.labelW : lx;

    if (city.dotR >= CITY_DOT_GRADIENT_THRESHOLD) {
      // Complex label: white fill + dark halo
      if (CITY_HALO_WIDTH > 0) {
        ctx.lineWidth   = CITY_HALO_WIDTH * 2;
        ctx.strokeStyle = CITY_HALO_COLOR;
        ctx.lineJoin    = 'round';
        ctx.strokeText(city.label, tx, ly);
      }
      ctx.fillStyle = CITY_LABEL_COLOR;
    } else {
      // Simple label: plain black fill, no halo
      ctx.fillStyle = CITY_LABEL_COLOR_SIMPLE;
    }
    ctx.fillText(city.label, tx, ly);
    if (city.rtl) ctx.direction = 'ltr';
  }

  ctx.restore();

  return { labels: placements.length, candidates: labelCandidates.length };
}

// ================================================================
// SCALE BAR
// ================================================================

// Project a lat/lon to canvas pixel coordinates (with tilt + viewOrigin).
function projectToCanvas(lat, lon) {
  return project(new LatLon(lat, lon))
    .rotate(MAP_TILT)
    .translate(viewOrigin)
    .scale(canvasPerSvg);
}

// Haversine great-circle distance in km.
function haversineKm(lat1, lon1, lat2, lon2) {
  const R   = 6371;
  const rad = d => d * Math.PI / 180;
  const a   = Math.sin(rad(lat2 - lat1) / 2) ** 2
            + Math.cos(rad(lat1)) * Math.cos(rad(lat2))
            * Math.sin(rad(lon2 - lon1) / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

// Newton-Raphson inverse projection: find the (lat, lon) that maps to
// canvas pixel (tx, ty), starting from initial guess (lat0, lon0).
function canvasInverse(tx, ty, lat0, lon0) {
  let lat = lat0, lon = lon0;
  const h = 1e-4; // degree perturbation for numerical Jacobian
  for (let i = 0; i < 100; i++) {
    const p  = projectToCanvas(lat, lon);
    const fx = p.x - tx, fy = p.y - ty;
    if (Math.abs(fx) < 0.01 && Math.abs(fy) < 0.01) break;
    const pLat = projectToCanvas(lat + h, lon);
    const pLon = projectToCanvas(lat, lon + h);
    const dxdl = (pLat.x - p.x) / h, dydl = (pLat.y - p.y) / h;
    const dxdn = (pLon.x - p.x) / h, dydn = (pLon.y - p.y) / h;
    const det  = dxdl * dydn - dxdn * dydl;
    lat += -(dydn * fx - dxdn * fy) / det;
    lon += -(-dydl * fx + dxdl * fy) / det;
  }
  return { lat, lon };
}

function drawScaleBar() {
  const targetPx = SCALE_BAR_LENGTH_MM / 25.4 * DPI;

  // Left anchor in canvas space
  const p1 = projectToCanvas(SCALE_BAR_ANCHOR_LAT, SCALE_BAR_ANCHOR_LON);

  // Target right-end canvas position (same y = perfectly horizontal)
  const tx = p1.x + targetPx;
  const ty = p1.y;

  // Rough initial guess for the right-end longitude:
  // use the empirically measured scale of ~2.84 km/px, 1° lon at anchor lat ≈ 71.5 km
  const approxKm   = targetPx * 2.84;
  const approxDlon = approxKm / (111.19 * Math.cos(SCALE_BAR_ANCHOR_LAT * Math.PI / 180));
  const { lat: lat2, lon: lon2 } =
    canvasInverse(tx, ty, SCALE_BAR_ANCHOR_LAT, SCALE_BAR_ANCHOR_LON + approxDlon);

  const distKm    = Math.round(haversineKm(SCALE_BAR_ANCHOR_LAT, SCALE_BAR_ANCHOR_LON, lat2, lon2));
  const distLabel = `${distKm.toLocaleString()} km`;

  console.log(`Scale bar: ${SCALE_BAR_LENGTH_MM} mm = ${distKm} km` +
    `  (P1 ${SCALE_BAR_ANCHOR_LAT}°N ${SCALE_BAR_ANCHOR_LON}°W →` +
    `  P2 ${lat2.toFixed(3)}°N ${lon2.toFixed(3)}°E)`);

  const x1 = p1.x, y1 = p1.y;
  const segPx = 10 / 25.4 * DPI;             // 1 cm in pixels
  const nSegs = Math.round(targetPx / segPx);
  const barH  = SCALE_BAR_TICK_H;

  ctx.save();

  // Alternating black/white filled segments
  for (let i = 0; i < nSegs; i++) {
    ctx.fillStyle = i % 2 === 0 ? 'rgba(0,0,0,0.5)' : 'rgba(255,255,255,0.7)';
    ctx.fillRect(x1 + i * segPx, y1 - barH / 2, segPx, barH);
  }

  // Thin dark outline over the whole bar for contrast on any background
  ctx.strokeStyle = SCALE_BAR_SHADOW;
  ctx.lineWidth   = mm(0.17);
  ctx.strokeRect(x1, y1 - barH / 2, targetPx, barH);

  // Label centred below the bar
  ctx.font         = `${SCALE_BAR_FONT_SIZE}px ${CITY_FONT_FAMILY}`;
  ctx.textAlign    = 'center';
  ctx.textBaseline = 'top';
  const lx = x1 + targetPx / 2;
  const ly = y1 + barH / 2 + 6;
  ctx.fillStyle = SCALE_BAR_SHADOW;
  ctx.fillText(distLabel, lx + 2, ly + 2);
  ctx.fillStyle = SCALE_BAR_COLOR;
  ctx.fillText(distLabel, lx, ly);

  ctx.restore();
}

// ================================================================

console.log(`Canvas: ${CANVAS_WIDTH}×${CANVAS_HEIGHT} px  (A0 landscape @ ${DPI} DPI)`);
console.log(`Map scale: ${canvasPerSvg.toFixed(2)} px/SVG unit — ` +
            `vertical margin: ${Math.round(yOffsetSvg * canvasPerSvg)} px each side`);

const t0 = Date.now();
MAP_AREAS.forEach((area, idx) => {
  drawMapArea(area, idx);
  process.stdout.write(`\rRendering … area ${idx + 1}/${MAP_AREAS.length}`);
});
console.log(`\nRendered in ${((Date.now() - t0) / 1000).toFixed(1)} s`);

// ------------------------------------------------------------------
// Fill 1-2 px seam gaps between octants.
// Adjacent octants' conformal mappings produce slightly different canvas
// positions for the shared boundary meridian.  Rather than expanding masks
// (which breaks inverse mapping), we detect unwritten pixels (alpha=0) that
// are surrounded by written ones and fill them from their neighbours.

process.stdout.write('Filling seam gaps … ');
{
  const d  = imageData.data;
  const w  = CANVAS_WIDTH;
  const nc = NUM_DEST_CHANNELS;
  let filled = 0;

  for (let y = 1; y < CANVAS_HEIGHT - 1; y++) {
    for (let x = 1; x < w - 1; x++) {
      const i = (y * w + x) * nc;
      if (d[i + 3] !== 0) continue;                     // already written

      const nb = [
        ((y - 1) * w + x) * nc,
        ((y + 1) * w + x) * nc,
        (y * w + (x - 1)) * nc,
        (y * w + (x + 1)) * nc,
      ];
      let n = 0, r = 0, g = 0, b = 0;
      for (const j of nb) {
        if (d[j + 3] === 0) continue;                   // also unwritten
        n++; r += d[j]; g += d[j + 1]; b += d[j + 2];
      }
      if (n >= 3) {                                      // isolated gap pixel
        d[i]     = Math.round(r / n);
        d[i + 1] = Math.round(g / n);
        d[i + 2] = Math.round(b / n);
        d[i + 3] = MAX_COLOR_VALUE;
        filled++;
      }
    }
  }
  // Make all remaining unwritten pixels opaque (background)
  for (let i = 3; i < d.length; i += 4) {
    if (d[i] === 0) d[i] = MAX_COLOR_VALUE;
  }
  console.log(`${filled} pixels filled`);
}

// ------------------------------------------------------------------
// Write pixel data, then overlay city labels

ctx.putImageData(imageData, 0, 0);

process.stdout.write('Drawing city labels … ');
const { labels, candidates } = await drawCityLabels();
console.log(`${labels}/${candidates} labels placed (dots only for labelled cities)`);

drawScaleBar();

// Pass raw pixel data directly to sharp to avoid a redundant encode/decode cycle.
// For fast iteration, change OUTPUT_FILE to end in .jpg (lossy but ~10× faster to write).
process.stdout.write(`Writing ${OUTPUT_FILE} … `);
const t1 = Date.now();
const finalData = ctx.getImageData(0, 0, CANVAS_WIDTH, CANVAS_HEIGHT);
await sharp(Buffer.from(finalData.data.buffer), {
  raw: { width: CANVAS_WIDTH, height: CANVAS_HEIGHT, channels: 4 },
  limitInputPixels: false,
})
  .withMetadata({ density: DPI })
  .toFile(OUTPUT_FILE);

console.log(`done in ${((Date.now() - t1) / 1000).toFixed(1)} s`);
